main: io.github.dode5656.easykits.EasyKits
version: 1.0.0
name: EasyKits
description: A easy to use Kits plugin.
author: dode5656
commands:
  kits:
    usage: /<command>
    permission: easykits.use
  kit:
    usage: /<command> <kit>
    permission: easykits.kit
permissions:
  easykits.kit.*:
    description: Access to claim a kit.
  easykits.kit:
    description: Acess to claim a kit.
  easykits.kit.others:
    description: Access to give a kit to others
  easykits.use:
    description: Access to kits gui.
  easykits.help:
    description: Access to kits help.
  easykits.admin:
    description: Access to admin commands.
  easykits.reload:
    description: Access to reload config.
  easykits.edit:
    description: Access to edit kits.

